# Generated by Django 2.1.3 on 2018-11-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('default', 'Default'), ('amelia', 'Amelia'), ('cerulean', 'Cerulean'), ('cosmo', 'Cosmo'), ('cyborg', 'Cyborg'), ('flatly', 'Flatly'), ('journal', 'Journal'), ('readable', 'Readable'), ('simplex', 'Simplex'), ('slate', 'Slate'), ('spacelab', 'SpaceLab'), ('united', 'United'), ('superhero', 'Superhero'), ('lumen', 'Lumen')], default='default', max_length=255)),
            ],
        ),
    ]
