# Generated by Django 2.1.3 on 2018-11-07 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_auto_20181107_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
    ]
